### ISSUE TITLE
Refresh pagina statiste sito

### ISSUE THREAD

**Issue by vsarnataro** [GruppoPBDMNG-5/ShortLink#8]
Se si prova a fare il refresh non funziona più la view. Prova a sto punto a fare una richiesta GET al server per prendere i dati necessari così risolviamo anche l'inconsistenza dei dati (prova a generare un link da zero ed entra una volta se cliccki sulle statistiche ti esce sempre 0)

**Comment by davidemenga** [comment]
Si ho notato, provvederò ad un fix

**Comment by davidemenga** [comment]
Risolto con commit 16470ab48ef6679af57dcddd8d430ab278460112
