### ISSUE TITLE
Errore indirizzamento LONG URL

### ISSUE THREAD

**Issue by gioelegentile** [GruppoPBDMNG-5/ShortLink#9]
Nella pagina di statistiche dell'url (provane uno a caso), se si clicca sul LONG URL (tipo www.google.com), si apre una finestra col link "localhost:8080/www.google.com" e ovviamente da errore. Ci dev'essere un'errore nell'ng-href

**Comment by vsarnataro** [comment]
fix con commit 41c1bb630a6eca5d75ae6d06ec544eb25215bbaa
